# Generated by Django 3.2.8 on 2021-10-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20211010_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipmentTag',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
