# Generated by Django 3.2.8 on 2021-10-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_troubleshooting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('can_see_dashboard', 'Can see all'),)},
        ),
    ]
